### ISSUE TITLE
Possible EventEmitter memory leak

### ISSUE THREAD

**Issue by sak1sham** [sak1sham/open-commerce#22]
**Issue:** 
I get this warning while trying to use the backend routes:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [SequelizeStore]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at SequelizeStore.addListener (node:events:605:10)
    at session (\open-commerce\backend\node_modules\express-session\index.js:172:9)
    at sessionMiddleware (\open-commerce\backend\middleware\auth\expressSession.ts:15:35)
    at Layer.handle [as handle_request] (\open-commerce\backend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (\open-commerce\backend\node_modules\express\lib\router\index.js:328:13)
    at \open-commerce\backend\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (\open-commerce\backend\node_modules\express\lib\router\index.js:346:12)
    at next (\open-commerce\backend\node_modules\express\lib\router\index.js:280:10)
```

**How to replicate this issue:**
1. Try running the backend server
2. Then login to an account (or signup)
3. Then make 11 consecutive POST requests to the /auth/signup route (with correct parameters)
4. At the 11th request, this warning will occur

Anyone knows how to resolve this error? Seems like this is an `express-session` library issue.

**Comment by sak1sham** [comment]
PR #23 has resolved this issue now.
